[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "construx3d"
version = "0.1.0"
description = "Editor 3D em tempo real controlado por gestos usando Python, OpenCV e MediaPipe."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "mediapipe==0.10.33",
  "numpy==2.4.2",
  "opencv-python==4.13.0.92"
]

[project.scripts]
construx3d = "construx3d.app:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
